version: "3.9"

services:
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: audio_transition
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#  server:
#    image: golang:latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    env_file:
#      - .env
#    volumes:
#      - ./storage:/go/src/app/storage

volumes:
  mysql_data: